name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5
      - name: Set up GCC
        run: |
          sudo apt install gcc g++ -y
        shell: bash
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - name: Start SMSC
        run: |
          g++ example/smsc_simulator/smsc.cpp -o smsc
          ./smsc &
        shell: bash
      - name: Test Coverage
        run: go test -v -race -count=1 -coverprofile=coverage.out
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1
        with:
          version: latest
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
